//
//  ScannerPresenter.swift
//  QRCodeReader
//
//  Created Padalingam A on 4/7/17.
//  Copyright © 2017 AppCoda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScannerPresenter: ScannerPresenterProtocol {

    weak private var view: ScannerViewProtocol?
    private let interactor: ScannerInteractorProtocol
    private let router: ScannerWireframeProtocol

    init(interface: ScannerViewProtocol, interactor: ScannerInteractorProtocol, router: ScannerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router

        self.interactor.presenter = self
    }

}
