//
//  ScannerRouter.swift
//  QRCodeReader
//
//  Created Padalingam A on 4/7/17.
//  Copyright © 2017 AppCoda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ScannerRouter: ScannerWireframeProtocol {

}
