//
//  ScannerProtocols.swift
//  QRCodeReader
//
//  Created Padalingam A on 4/7/17.
//  Copyright © 2017 AppCoda. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ScannerWireframeProtocol: class {

}
//MARK: Presenter -
protocol ScannerPresenterProtocol: class {

}

//MARK: Interactor -
protocol ScannerInteractorProtocol: class {

  var presenter: ScannerPresenterProtocol?  { get set }
}

//MARK: View -
protocol ScannerViewProtocol: class {

  var presenter: ScannerPresenterProtocol?  { get set }
}
